from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "content" / "drafts" / "animations" / "differential-noether-two-readings.png"

WIDTH = 1320
HEIGHT = 620


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    names = ["arialbd.ttf" if bold else "arial.ttf", "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"]
    for name in names:
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


FONT_TITLE = font(34, True)
FONT_EQUATION = font(36)
FONT_LABEL = font(26, True)
FONT_TEXT = font(22)
FONT_SMALL = font(18)

INK = (32, 33, 36)
MUTED = (92, 92, 92)
LINE = (196, 196, 196)
BLUE = (53, 80, 112)
RED = (188, 71, 73)
PAPER = (255, 253, 248)
PANEL = (248, 247, 243)


def rounded_label(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], title: str, body: str, color: tuple[int, int, int]) -> None:
    x0, y0, x1, y1 = box
    draw.rounded_rectangle(box, radius=18, fill=PANEL, outline=color, width=3)
    draw.text(((x0 + x1) / 2, y0 + 30), title, fill=color, font=FONT_LABEL, anchor="ma")
    draw.multiline_text(
        ((x0 + x1) / 2, y0 + 78),
        body,
        fill=INK,
        font=FONT_TEXT,
        anchor="ma",
        align="center",
        spacing=8,
    )


def arrow(draw: ImageDraw.ImageDraw, start: tuple[int, int], end: tuple[int, int], color: tuple[int, int, int]) -> None:
    draw.line((*start, *end), fill=color, width=5)
    x, y = end
    draw.polygon([(x, y), (x - 11, y - 20), (x + 11, y - 20)], fill=color)


def main() -> None:
    image = Image.new("RGB", (WIDTH, HEIGHT), PAPER)
    draw = ImageDraw.Draw(image)

    draw.text((WIDTH / 2, 48), "One vanishing bracket, two Noether readings", fill=INK, font=FONT_TITLE, anchor="ma")

    equation_box = (330, 110, 990, 205)
    draw.rounded_rectangle(equation_box, radius=20, fill=(255, 255, 255), outline=LINE, width=2)
    draw.text((WIDTH / 2, 155), "{f,H} = 0 = {H,f}", fill=INK, font=FONT_EQUATION, anchor="ma")
    draw.text((WIDTH / 2, 232), "the same zero relation read from opposite sides", fill=MUTED, font=FONT_SMALL, anchor="ma")

    left_box = (86, 365, 586, 548)
    right_box = (734, 365, 1234, 548)

    arrow(draw, (500, 214), (330, 350), BLUE)
    arrow(draw, (820, 214), (990, 350), RED)

    draw.text((340, 255), "read as {f,H}", fill=BLUE, font=FONT_SMALL, anchor="ma")
    draw.text((980, 255), "read as {H,f}", fill=RED, font=FONT_SMALL, anchor="ma")

    rounded_label(
        draw,
        left_box,
        "Conservation",
        "f does not change\nalong the time flow\ngenerated by H",
        BLUE,
    )
    rounded_label(
        draw,
        right_box,
        "Symmetry",
        "the flow generated by f\nleaves H unchanged\nso that flow is a symmetry",
        RED,
    )

    draw.text(
        (WIDTH / 2, 595),
        "If the bracket vanishes, conservation and symmetry are two readings of the same algebraic relation.",
        fill=MUTED,
        font=FONT_SMALL,
        anchor="ma",
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    image.save(OUTPUT)
    print(OUTPUT)


if __name__ == "__main__":
    main()
